// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_gFPOksF8IAXeWUW2Sh0vdTpV8THTjUw',
    appId: '1:924241672666:web:f742e49476290a54d428e3',
    messagingSenderId: '924241672666',
    projectId: 'bmical-ac87d',
    authDomain: 'bmical-ac87d.firebaseapp.com',
    storageBucket: 'bmical-ac87d.firebasestorage.app',
    measurementId: 'G-ND5ZH0TBGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFO64Rak89tLRB-xZsUCuJVPA8vQf-P4M',
    appId: '1:924241672666:android:8b0dc796fdf1eb45d428e3',
    messagingSenderId: '924241672666',
    projectId: 'bmical-ac87d',
    storageBucket: 'bmical-ac87d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArro40w_2A4TdGVgtQdg3XLNNWACTQnV0',
    appId: '1:924241672666:ios:567ee3007c3519cad428e3',
    messagingSenderId: '924241672666',
    projectId: 'bmical-ac87d',
    storageBucket: 'bmical-ac87d.firebasestorage.app',
    iosClientId: '924241672666-ffn1hn0goe5ib8t9p3ptiurblotol12l.apps.googleusercontent.com',
    iosBundleId: 'com.ivinnovations.bmiTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArro40w_2A4TdGVgtQdg3XLNNWACTQnV0',
    appId: '1:924241672666:ios:567ee3007c3519cad428e3',
    messagingSenderId: '924241672666',
    projectId: 'bmical-ac87d',
    storageBucket: 'bmical-ac87d.firebasestorage.app',
    iosClientId: '924241672666-ffn1hn0goe5ib8t9p3ptiurblotol12l.apps.googleusercontent.com',
    iosBundleId: 'com.ivinnovations.bmiTracker',
  );
}
